repos:
  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: ['--pre-summary-newline', '--wrap-summaries', '132', '--wrap-descriptions', '132', --in-place]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.1.1
    hooks:
      - id: pydocstyle
        args: ['--convention', 'pep257', '--add-ignore', 'D100, D107, D104, D105']
        exclude: '^(tests/|setup.py|ntgen/__main__.py)'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
      - id: pretty-format-json
        exclude: '^acceptance'
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: '^acceptance'
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.7
        args: ['--line-length', '131']

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
      - id: reorder-python-imports
        args: [--py37-plus]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: ['--ignore', 'E231', '--max-line-length', '131']
        exclude: '^(tests/end_to_end/module_template.py|ntgen/__init__.py)$'

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        exclude: '^tests/$'
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.0
    hooks:
      - id: python-use-type-annotations
