version: 2.1

jobs:
  base-template: &base_template
    docker:
      - image: python:3.8
    steps: &base_cmds
      - checkout
      - run:
          command: |
            echo "export PATH=$HOME/.local/bin:$PATH" >> $BASH_ENV
            source $BASH_ENV
            pip install tox
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
            source "${HOME}/.profile"
            make test
  build-py37:
    <<: *base_template
    docker:
      - image: python:3.7
  build-py38: *base_template
  build-coverage:
    <<: *base_template
    steps:
      *base_cmds
      - <: *base_cmds
      - run:
          command: |
            echo "repo_token: ${COVERALLS_TOKEN}" > .coveralls.yml
            echo "export PATH=$HOME/.local/bin:$PATH" >> $BASH_ENV
            source $BASH_ENV
            make dev
            make submit_coverage
  build-acceptance:
    <<: *base_template
    steps:
      - checkout
      - run:
          command: make acceptance
workflows:
  version: 2
  build:
    jobs:
      - build-py37
      - build-py38
      - build-coverage
      - build-acceptance
