version: 2
jobs:
  base-template: &base_template
    docker:
      - image: python:3.8
    working_directory: ~/ntgen
    steps:
      - checkout
      - run:
          command: |
            echo "export PATH=$HOME/.local/bin:$PATH" >> $BASH_ENV
            source $BASH_ENV
            make test
  build-py36:
    <<: *base_template
    docker:
      - image: python:3.6
  build-py37:
    <<: *base_template
    docker:
      - image: python:3.7
  build-py38: *base_template
  build-coverage:
    <<: *base_template
    steps:
      - checkout
      - run:
          command: |
            echo "repo_token: ${COVERALLS_TOKEN}" > .coveralls.yml
            echo "export PATH=$HOME/.local/bin:$PATH" >> $BASH_ENV
            source $BASH_ENV
            make submit_coverage
workflows:
  version: 2
  build:
    jobs:
      - build-py36
      - build-py37
      - build-py38
      - build-coverage
